# Generated by Django 4.2.1 on 2023-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_phone_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
