# Generated by Django 4.2.1 on 2023-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_order_order_by_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_by',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
