# Generated by Django 4.2.1 on 2023-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_phone_number',
            new_name='customer_phone_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_by_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_by_staff',
        ),
        migrations.AddField(
            model_name='order',
            name='order_by',
            field=models.CharField(choices=[('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
    ]
