# Generated by Django 4.2.1 on 2023-06-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_phone_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='Phone',
            new_name='phone',
        ),
    ]
