# Generated by Django 4.2.1 on 2023-06-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_phone_phone_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
